### ISSUE TITLE
New build with LocalTalk over UDP?

### ISSUE THREAD

**Issue by RolandJuno** [zzxzzk115/Pocketchip-MacOS-Emulator#1]
Greetings! Would it be possible for to you create a build of Mini VMac for Pocketchip that enables LocalTalk over UDP?

-lto udp

Cheers!

**Comment by zzxzzk115** [comment]
Sure, I'll have a try during my leisure time. It seems that PocketCHIP can talk with another device which enables LocalTalk. That's pretty cool. 😀

**Comment by zzxzzk115** [comment]
I found that minivmac enabled this feature by default after version 37, which means that there is no need to build with -lto udp.

**Comment by RolandJuno** [comment]
Thanks! Yes, the default LocalTalk option is UDP but LocalTalk still needs to be enabled (default is disabled) with the -lt option. I was able to build it myself on the PocketChip. Here's the setup string I used.

`./setup_t -t larm -m II -lt -lto udp -speed z -hres 480 -vres 272 -fullscreen 1 -emm 0 > setup.sh
`

1x speed is crucial as it will crash otherwise (however, it seems that you can boost the speed after you get to the desktop).

I was able to use an AirTalk ( http://airtalk.shop/ ) to see an ImageWriter II with AppleTalk card installed.
https://mastodon.social/@paulrickards/110458959693910947

Happy to submit a binary as well.

Cheers,

**Comment by zzxzzk115** [comment]
Amazing! You can submit a PR if you want. 😄

**Comment by zzxzzk115** [comment]
Thanks, 

Here is the instruction:

Download beta source first:
https://www.gryphel.com/d/minivmac/minivmac-37.03/minivmac-37.03.src.tgz

Upload to PocketCHIP, and use SSH to connect to PocketCHIP:

```bash
tar -xvzf minivmac-37.03.src.tgz
cd minivmac
gcc setup/tool.c -o setup_t
./setup_t -t larm -m II -lt -lto udp -speed z -hres 480 -vres 272 -fullscreen 1 -emm 0 > setup.sh
chmod +x setup.sh
./setup.sh
make
```
